export const Booklist = [
  {
    id: crypto.randomUUID(),
    name: "The Lean Startup : The Million Copy Bestseller Driving Entrepreneurs to Success",
    author: "RIES ERIC",
    img: "https://m.media-amazon.com/images/I/81vvgZqCskL._AC._SR360,460.jpg",
    price: 560.69,
    rating: 5,
    publish: 2019, 
    isFav: false,
  },
  {
    id: crypto.randomUUID(),
    name: "Python Tricks: A Buffet Of Awesome Python Features Deep",
    author: "Dan Bader",
    img: "https://m.media-amazon.com/images/I/61k7Z74UuZL._AC._SR360,460.jpg",
    price: 313.0,
    rating: 4,
    publish: 2018,
    isFav: false,
  },
  {
    id: crypto.randomUUID(),
    name: "Computer Hacking Beginners Guide: How to Hack Wireless Network",
    author: " Alan T. Norman",
    img: "https://m.media-amazon.com/images/I/71eylXCopqL._AC._SR360,460.jpg",
    price: 223.0,
    rating: 5,
    publish: 2020,
    isFav: false,
  },
  {
    id: crypto.randomUUID(),
    name: "Let Us C: Authentic guide to C programming language - 19th Edition",
    author: "Yashavant Kanetkar",
    img: "https://m.media-amazon.com/images/I/81ZPcK6HpuL._AC._SR360,460.jpg",
    price: 326.0,
    rating: 3,
    publish: 2019,
    isFav: false,
  },
  {
    id: crypto.randomUUID(),
    name: "Learn Python in One Day and Learn It Well. Python",
    author: "LCF Publishing",
    img: "https://m.media-amazon.com/images/I/81tncJ5sO6L._UX300_PJku-sticker-v7,TopRight,0,-50._AC._SR360,460_.jpg",
    price: 249.0,
    rating: 4,
    publish: 2018,
    isFav: false,
  },
  {
    id: crypto.randomUUID(),
    name: "The Lean Startup : The Million Copy Bestseller Driving Entrepreneurs to",
    author: "RIES ERIC",
    img: "https://m.media-amazon.com/images/I/81vvgZqCskL._AC._SR360,460.jpg",
    price: 560.69,
    rating: 4,
    publish: 2020,
    isFav: false,
  },
  {
    id: crypto.randomUUID(),
    name: "Eloquent Javascript 3E: A Modern Introduction to Programming",
    author: "Marijn Haverbeke",
    img: "https://m.media-amazon.com/images/I/81HqVRRwp3L._AC._SR360,460.jpg",
    price: 2699,
    rating: 5,
    publish: 2019,
    isFav: false,
  },
  {
    id: crypto.randomUUID(),
    name: "Harshil Chovatiya",
    author: "RIES ERIC",
    img: "https://m.media-amazon.com/images/I/61Hpl2Y7xHL._UX300_PJku-sticker-v7,TopRight,0,-50._AC._SR360,460_.jpg",
    price: 99,
    rating: 4,
    publish: 2021,
    isFav: false,
  },
];
